on:
  push

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          
      - name: Setup The Internet App
        run: docker run -d -p 8080:5000 gprestes/the-internet
        
      - name: Run Tests
        run: |
          cd ui/cypress
          npm install
          npm run -s cypress:run -- --env username=tomsmith,password=SuperSecretPassword! --spec cypress/e2e/sign-in.cy.js